USE [master]
GO

/****** Object:  Database [vacunas]    Script Date: 30/11/2021 5:59:34 ******/
CREATE DATABASE [vacunas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vacunas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\vacunas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'vacunas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\vacunas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vacunas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vacunas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vacunas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vacunas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vacunas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vacunas] SET ARITHABORT OFF 
GO

ALTER DATABASE [vacunas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [vacunas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vacunas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vacunas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vacunas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vacunas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vacunas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vacunas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vacunas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vacunas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [vacunas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vacunas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vacunas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vacunas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vacunas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vacunas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [vacunas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vacunas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vacunas] SET  MULTI_USER 
GO

ALTER DATABASE [vacunas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vacunas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vacunas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vacunas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [vacunas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [vacunas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [vacunas] SET QUERY_STORE = OFF
GO

ALTER DATABASE [vacunas] SET  READ_WRITE 
GO

